# Generated by Django 2.0.13 on 2019-04-21 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('estabelecimento', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=7)),
                ('filtro', models.CharField(max_length=15)),
                ('valor', models.FloatField()),
                ('cesta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cerveja.Cesta')),
            ],
        ),
    ]
