# Generated by Django 2.0.13 on 2019-04-21 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerveja', '0002_cesta_itemcesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcesta',
            name='descricao',
        ),
    ]
